@baseUrl = http://localhost:3000

### RecadosControllerGetFindAll

# @name RecadosControllerGetFindAll
GET {{baseUrl}}/recados/
?limit=10
&offset=0

### RecadosControllerGetFindOne

# @name RecadosControllerGetFindOne
GET {{baseUrl}}/recados/5

### RecadosControllerPostCreate

# @name RecadosControllerPostCreate
POST {{baseUrl}}/recados/
Content-Type: application/json

{
  "recado":"Este é o recado que estou enviado",
  "nova chave": "outro valor"
}

### RecadosControllerPatchUpdate

# @name RecadosControllerPatchUpdate
PATCH {{baseUrl}}/recados/1
Content-Type: application/json

{
  "recado":"Este é o recado que estou enviado"
}

### RecadosControllerDeleteRemove

# @name RecadosControllerDeleteRemove
DELETE {{baseUrl}}/recados/1
