@baseUrl = http://localhost:3000

### RecadosControllerGetFindAll

# @name RecadosControllerGetFindAll
GET {{baseUrl}}/recados/
?limit=10
&offset=0

### RecadosControllerGetFindOne

# @name RecadosControllerGetFindOne
GET {{baseUrl}}/recados/2

### RecadosControllerPostCreate

# @name RecadosControllerPostCreate
POST {{baseUrl}}/recados/
Content-Type: application/json

  {
    "texto": "Novo recado",
    "de": "Joana",
    "para": "João",
    "lido": false,
    "data": "2026-08-23T22:00:21.985Z"
  }

### RecadosControllerPatchUpdate

# @name RecadosControllerPatchUpdate
PATCH {{baseUrl}}/recados/2
Content-Type: application/json

  {
    "texto": "atualiza recado",
    "de": "Joana",
    "para": "João",
    "lido": false,
    "data": "2026-08-23T22:00:21.985Z"
  }

### RecadosControllerDeleteRemove

# @name RecadosControllerDeleteRemove
DELETE {{baseUrl}}/recados/2
